@startuml
start
repeat
  :Read from topic;
  :Process message;
  if (Processing successful?) then (no)
    :Increment attempt number;
    if (Attempt < threshold?) then (yes)
      :Send to retry topic;
    else (no)
      :Send to error topic;
      stop
    endif
  else (yes)
    :Make POST request with data;
    stop
  endif
repeat while (Attempt < threshold?)
@enduml